# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\advik\Desktop\sample.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1341, 688)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(282, 10, 1051, 681))
        self.tabWidget.setObjectName("tabWidget")
        self.OLE = QtWidgets.QWidget()
        self.OLE.setObjectName("OLE")
        self.OLE_2 = QtWidgets.QTableView(self.OLE)
        self.OLE_2.setGeometry(QtCore.QRect(-5, 1, 1061, 981))
        self.OLE_2.setObjectName("OLE_2")
        self.tabWidget.addTab(self.OLE, "")
        self.VPR = QtWidgets.QWidget()
        self.VPR.setObjectName("VPR")
        self.VPR_2 = QtWidgets.QTableView(self.VPR)
        self.VPR_2.setGeometry(QtCore.QRect(-5, 1, 1061, 1001))
        self.VPR_2.setObjectName("VPR_2")
        self.tabWidget.addTab(self.VPR, "")
        self.OLEVSVPR = QtWidgets.QWidget()
        self.OLEVSVPR.setObjectName("OLEVSVPR")
        self.OLEVSVPR_2 = QtWidgets.QTableView(self.OLEVSVPR)
        self.OLEVSVPR_2.setGeometry(QtCore.QRect(-10, 0, 1081, 1011))
        self.OLEVSVPR_2.setObjectName("OLEVSVPR_2")
        self.tabWidget.addTab(self.OLEVSVPR, "")
        self.OUTPUT = QtWidgets.QWidget()
        self.OUTPUT.setObjectName("OUTPUT")
        self.OUTPUT_2 = QtWidgets.QTableView(self.OUTPUT)
        self.OUTPUT_2.setGeometry(QtCore.QRect(-10, 0, 1091, 641))
        self.OUTPUT_2.setObjectName("OUTPUT_2")
        self.tabWidget.addTab(self.OUTPUT, "")
        self.grpDB2Credentials = QtWidgets.QGroupBox(Form)
        self.grpDB2Credentials.setGeometry(QtCore.QRect(10, 537, 266, 154))
        self.grpDB2Credentials.setObjectName("grpDB2Credentials")
        self.pushButton_2 = QtWidgets.QPushButton(self.grpDB2Credentials)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 90, 241, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget = QtWidgets.QWidget(self.grpDB2Credentials)
        self.widget.setGeometry(QtCore.QRect(10, 30, 241, 101))
        self.widget.setObjectName("widget")
        self.frmDBCredentials = QtWidgets.QFormLayout(self.widget)
        self.frmDBCredentials.setContentsMargins(0, 0, 0, 0)
        self.frmDBCredentials.setObjectName("frmDBCredentials")
        self.lblUserName = QtWidgets.QLabel(self.widget)
        self.lblUserName.setObjectName("lblUserName")
        self.frmDBCredentials.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblUserName)
        self.InputvalUserName = QtWidgets.QLineEdit(self.widget)
        self.InputvalUserName.setObjectName("InputvalUserName")
        self.frmDBCredentials.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.InputvalUserName)
        self.lblPasswork = QtWidgets.QLabel(self.widget)
        self.lblPasswork.setObjectName("lblPasswork")
        self.frmDBCredentials.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblPasswork)
        self.InputValuePasswd = QtWidgets.QLineEdit(self.widget)
        self.InputValuePasswd.setObjectName("InputValuePasswd")
        self.frmDBCredentials.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.InputValuePasswd)
        self.grpOLEinput = QtWidgets.QGroupBox(Form)
        self.grpOLEinput.setGeometry(QtCore.QRect(10, 111, 266, 221))
        self.grpOLEinput.setObjectName("grpOLEinput")
        self.widget1 = QtWidgets.QWidget(self.grpOLEinput)
        self.widget1.setGeometry(QtCore.QRect(10, 30, 241, 171))
        self.widget1.setObjectName("widget1")
        self.frmOLEInput = QtWidgets.QFormLayout(self.widget1)
        self.frmOLEInput.setContentsMargins(0, 0, 0, 0)
        self.frmOLEInput.setObjectName("frmOLEInput")
        self.InputLab1 = QtWidgets.QLabel(self.widget1)
        self.InputLab1.setObjectName("InputLab1")
        self.frmOLEInput.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.InputLab1)
        self.InputVal1 = QtWidgets.QLineEdit(self.widget1)
        self.InputVal1.setEnabled(True)
        self.InputVal1.setObjectName("InputVal1")
        self.frmOLEInput.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.InputVal1)
        self.InputLab2 = QtWidgets.QLabel(self.widget1)
        self.InputLab2.setObjectName("InputLab2")
        self.frmOLEInput.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.InputLab2)
        self.InputVal2 = QtWidgets.QLineEdit(self.widget1)
        self.InputVal2.setObjectName("InputVal2")
        self.frmOLEInput.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.InputVal2)
        self.InputLab3 = QtWidgets.QLabel(self.widget1)
        self.InputLab3.setObjectName("InputLab3")
        self.frmOLEInput.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.InputLab3)
        self.InputVal3 = QtWidgets.QLineEdit(self.widget1)
        self.InputVal3.setObjectName("InputVal3")
        self.frmOLEInput.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.InputVal3)
        self.InputLab4 = QtWidgets.QLabel(self.widget1)
        self.InputLab4.setObjectName("InputLab4")
        self.frmOLEInput.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.InputLab4)
        self.InputVal4 = QtWidgets.QLineEdit(self.widget1)
        self.InputVal4.setObjectName("InputVal4")
        self.frmOLEInput.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.InputVal4)
        self.InputLab5 = QtWidgets.QLabel(self.widget1)
        self.InputLab5.setObjectName("InputLab5")
        self.frmOLEInput.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.InputLab5)
        self.InputLab6 = QtWidgets.QLabel(self.widget1)
        self.InputLab6.setObjectName("InputLab6")
        self.frmOLEInput.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.InputLab6)
        self.InputVal6 = QtWidgets.QLineEdit(self.widget1)
        self.InputVal6.setObjectName("InputVal6")
        self.frmOLEInput.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.InputVal6)
        self.InputVal5 = QtWidgets.QLineEdit(self.widget1)
        self.InputVal5.setObjectName("InputVal5")
        self.frmOLEInput.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.InputVal5)
        self.GroupOLEFilters = QtWidgets.QGroupBox(Form)
        self.GroupOLEFilters.setGeometry(QtCore.QRect(10, 338, 266, 193))
        self.GroupOLEFilters.setObjectName("GroupOLEFilters")
        self.widget2 = QtWidgets.QWidget(self.GroupOLEFilters)
        self.widget2.setGeometry(QtCore.QRect(10, 30, 241, 141))
        self.widget2.setObjectName("widget2")
        self.frmOLEFilters = QtWidgets.QFormLayout(self.widget2)
        self.frmOLEFilters.setContentsMargins(0, 0, 0, 0)
        self.frmOLEFilters.setObjectName("frmOLEFilters")
        self.Filter4 = QtWidgets.QLabel(self.widget2)
        self.Filter4.setObjectName("Filter4")
        self.frmOLEFilters.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Filter4)
        self.FilVal3 = QtWidgets.QLineEdit(self.widget2)
        self.FilVal3.setObjectName("FilVal3")
        self.frmOLEFilters.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.FilVal3)
        self.Filter2 = QtWidgets.QLabel(self.widget2)
        self.Filter2.setObjectName("Filter2")
        self.frmOLEFilters.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Filter2)
        self.FilVal1 = QtWidgets.QLineEdit(self.widget2)
        self.FilVal1.setObjectName("FilVal1")
        self.frmOLEFilters.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.FilVal1)
        self.Filter1 = QtWidgets.QLabel(self.widget2)
        self.Filter1.setObjectName("Filter1")
        self.frmOLEFilters.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Filter1)
        self.FilVal2 = QtWidgets.QLineEdit(self.widget2)
        self.FilVal2.setObjectName("FilVal2")
        self.frmOLEFilters.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.FilVal2)
        self.Filter3 = QtWidgets.QLabel(self.widget2)
        self.Filter3.setObjectName("Filter3")
        self.frmOLEFilters.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Filter3)
        self.FilVal4 = QtWidgets.QLineEdit(self.widget2)
        self.FilVal4.setObjectName("FilVal4")
        self.frmOLEFilters.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.FilVal4)
        self.Filter5 = QtWidgets.QLabel(self.widget2)
        self.Filter5.setObjectName("Filter5")
        self.frmOLEFilters.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Filter5)
        self.FilVal5 = QtWidgets.QLineEdit(self.widget2)
        self.FilVal5.setObjectName("FilVal5")
        self.frmOLEFilters.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.FilVal5)
        self.grpOLEFile = QtWidgets.QGroupBox(Form)
        self.grpOLEFile.setGeometry(QtCore.QRect(10, 10, 266, 95))
        self.grpOLEFile.setObjectName("grpOLEFile")
        self.widget3 = QtWidgets.QWidget(self.grpOLEFile)
        self.widget3.setGeometry(QtCore.QRect(10, 20, 241, 59))
        self.widget3.setObjectName("widget3")
        self.vLayOLEFile = QtWidgets.QVBoxLayout(self.widget3)
        self.vLayOLEFile.setContentsMargins(0, 0, 0, 0)
        self.vLayOLEFile.setObjectName("vLayOLEFile")
        self.PushOLEFILELoad = QtWidgets.QPushButton(self.widget3)
        self.PushOLEFILELoad.setObjectName("PushOLEFILELoad")
        self.vLayOLEFile.addWidget(self.PushOLEFILELoad)
        self.txtOLEFilePath = QtWidgets.QLineEdit(self.widget3)
        self.txtOLEFilePath.setEnabled(True)
        self.txtOLEFilePath.setObjectName("txtOLEFilePath")
        self.vLayOLEFile.addWidget(self.txtOLEFilePath)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OLE), _translate("Form", "OLE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.VPR), _translate("Form", "VPR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OLEVSVPR), _translate("Form", "OLE Vs VPR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OUTPUT), _translate("Form", "Output"))
        self.grpDB2Credentials.setTitle(_translate("Form", "QA2 DB Credential"))
        self.pushButton_2.setText(_translate("Form", "GET VPR DATA"))
        self.lblUserName.setText(_translate("Form", "User Id:"))
        self.lblPasswork.setText(_translate("Form", "Passwd:"))
        self.grpOLEinput.setTitle(_translate("Form", "OLE Input Parameters"))
        self.InputLab1.setText(_translate("Form", "Feed Ty:"))
        self.InputLab2.setText(_translate("Form", "Acct No:"))
        self.InputLab3.setText(_translate("Form", "View ty:"))
        self.InputLab4.setText(_translate("Form", "From Dt:"))
        self.InputLab5.setText(_translate("Form", "To Dt:"))
        self.InputLab6.setText(_translate("Form", "Date ty:"))
        self.GroupOLEFilters.setTitle(_translate("Form", "Additional OLE Input Filter"))
        self.Filter4.setText(_translate("Form", "Filter 1:"))
        self.Filter2.setText(_translate("Form", "Filter 2:"))
        self.Filter1.setText(_translate("Form", "Filter 3:"))
        self.Filter3.setText(_translate("Form", "Filter 4:"))
        self.Filter5.setText(_translate("Form", "Filter 5:"))
        self.grpOLEFile.setTitle(_translate("Form", "OLE Input File"))
        self.PushOLEFILELoad.setText(_translate("Form", "GET VPR DATA"))

